log_dir: Log/NTU-RGB+D60/xview/

epoch: 100
device: [0,1]

# model
model_args:
  num_class: 60
  in_channels: 3
  residual: True
  dropout: 0.5
  num_person: 2
  t_kernel_size: 9
  layout: 'ntu-rgb+d'
  strategy: 'spatial'
  hop_size: 3
  load_weight: False
  weight_path: Log/NTU-RGB+D60/xview/test/best_model.pt

# optimizer
optimizer_args:
  optimizer: SGD
  base_lr: 0.1
  lr_step: [40, 70, 90]

# feeder
feeder_args:
  frame_size: 300
  batch_size: 64
  num_worker: 0
  train_feeder_args:
    data_path: /root/shiraki/dataset/gen_ntu_data/NTU-RGB+D60/xview/train_coordinate.npy
    label_path: /root/shiraki/dataset/gen_ntu_data/NTU-RGB+D60/xview/train_label.pkl
    normalization: False
    random_shift: False
    valid_choose: False
    frame_thinning: False
    random_choose: False
    repeat_padding: True
    random_move: True
    add_noise: False
    frame_normalization: False
  test_feeder_args:
    data_path: /root/shiraki/dataset/gen_ntu_data/NTU-RGB+D60/xview/test_coordinate.npy
    label_path: /root/shiraki/dataset/gen_ntu_data/NTU-RGB+D60/xview/test_label.pkl
    normalization: False
    random_shift: False
    valid_choose: False
    frame_thinning: False
    random_choose: False
    repeat_padding: True
    random_move: True
    add_noise: False
    frame_normalization: False